Feature/minerva noe
DUNE/ND_CAFMaker pull request #39
Opened 2023-11-13 14:29 UTC by noeroy

MINERvA reco for NDCafMaker

Added the Minerva Branch Fille class and methods

Added Minerva into the parameter list and the CafMaker loop

2023-11-14 20:20 UTC, chenel requested changes
Thank you so much for this!

The vast majority of it looks fine to me with only a few nitpicks.  The major thing I'm concerned about is the explicit loops through the true particle hierarchy, which I'd really like done instead via the dedicated `TruthMatcher::GetTrueParticle()` method in order to keep the logic in a single place.  See notes below.

2023-11-14 20:20 UTC, chenel commented on src/reco/MINERvARecoBranchFiller.cxx
> +    part.end_pos = caf::SRVector3D(mc_traj_point_x[max_trkid][1],mc_traj_point_y[max_trkid][1],mc_traj_point_z[max_trkid][1]);
I think rather than creating a particle from scratch here you should instead be using the `TruthMatcher`'s `GetTrueParticle()` method, which works just like the `GetTrueInteraction()` one that you used below.  That will ensure you're never making duplicates, and can replace the 3-way branch you're doing below.  (see notes there)

2023-11-14 20:20 UTC, chenel commented on src/reco/MINERvARecoBranchFiller.cxx
> +  }
I'd really prefer you used the `TruthMatcher::GetTrueParticle()` method here rather than searching for / creating new particles explicitly.  If anything in the underlying implementation changes, this code could break unexpectedly, and it's better to have the "search for particle" code centralized in one place.  `GetTrueParticle()` should do everything you're doing here, and you can update the particle once it's returned to you if you need to.  (See the `ValidateOrCopy()` calls in the `MLNDLArRecoBranchFiller` for a clean way to do these updates.)

2023-11-14 20:20 UTC, chenel commented on src/reco/MINERvARecoBranchFiller.cxx
> +    part.end_pos = caf::SRVector3D(mc_traj_point_x[max_trkid][1],mc_traj_point_y[max_trkid][1],mc_traj_point_z[max_trkid][1]);
same comment as in the `track` version

2023-11-14 20:20 UTC, chenel commented on src/reco/MINERvARecoBranchFiller.cxx
> +    }
same comment as in the track version

2023-11-16 22:26 UTC, noeroy commented on src/makeCAF.C
> +      //if (triggersByFiller.size() == 0) break;
Fixed

2023-11-16 22:27 UTC, noeroy commented on src/reco/MINERvARecoBranchFiller.h
> +      }
Moved to `.cxx`

2023-11-16 22:30 UTC, noeroy commented on src/reco/MINERvARecoBranchFiller.cxx
> +  }
Followed the `MLNDLArRecoBranchFiller ` like implementation.
Had to "cheat" a bit to look for the primary, if we get a flag directly in Edepsim it will make things simpler.

Some Passthrough infomation are missing for to get the full `ValidateOrCopy()` working on things like position and momentum.

2023-11-16 22:30 UTC, noeroy commented on src/reco/MINERvARecoBranchFiller.cxx
> +    part.end_pos = caf::SRVector3D(mc_traj_point_x[max_trkid][1],mc_traj_point_y[max_trkid][1],mc_traj_point_z[max_trkid][1]);
Same comment as in the `track` version too

2023-11-17 14:49 UTC, chenel approved these changes
Okay!  I'm happy with where things are at now, pending testing that we're actually still matching correctly after all the changes.  I'm happy to help debug further however if we still are having trouble not repeating particle creation using the `GetTrueParticle()` method in the truthmatcher.

2023-11-17 16:05 UTC, merged