Feature/edepsim truth
DUNE/ND_CAFMaker pull request #77
Opened 2024-08-27 20:16 UTC by noeroy

Added Truth reading from Edepsim:

- Contains a new library for the Edepsim files and the method to build it that is called in build.sh

- Edepsim files are the merged spill files used by simulations.

- Edepsim files are loaded the same way as other files with the call 
`nd_cafmaker.CAFMakerSettings.EdepsimFile: "/path/to/edepsimfile.root"`

- Edepsim Files are read when filling the true interactions (`FillInteraction` in `FillTruth.cxx` and to get particles in `FillParticle` in `FillTruth.cxx`.
We select the right entry from the Edepsim file with the combination of RunId and EventId exactly as the GenieFiles. 

Three modifications were made to  `MLNDLArRecoBranchFiller`:
  - G4 ID is explicitely passed
  - G4ID is always defined as the gen_id of the file
  - We don't try to match ancestors inside it as the link is sometimes broken in MLReco

Added a template for `ValidateOrCopy` for `float float` comparisons. And loosened the criteria (apparently 1e-6 was too tight)

Those additions have fixed several issues realted to [#71](https://github.com/DUNE/ND_CAFMaker/issues/71), #63 and another issue with neutral particles not being stored properly.

Details can be found in [DocDb #31466](https://docs.dunescience.org/cgi-bin/sso/RetrieveFile?docid=31466&filename=Truth_matching_in_cafs.pdf&version=1)

Impact x-checks show:
- An additional running time of **40% (1.4 min vs 1min in average for a MiniRun5 file)**, still way bellow the bottlenecks of the production chain
- **No impact on the CPU usage** per process
- **Additional filesize that needs to be accessible is 60%**: For Minrun5, 791G for Genie and 536G for edepsim. Prelminiary work shows me that we can drop the memory usage of edepsim files by 50-60% by removing irrelevant variables for that work (Segments, Primaries, intermediate points) in case we want to store the full file on tape and keep a reduced file for future reprocessing.

2024-08-29 16:38 UTC, chenel requested changes
Okay.  I've read through most of this, though I haven't worked through every last change super carefully (including the new truth-matching function implementations).  I have a few nitpicks and questions on the code itself, but there's one bigger issue that I'd like to discuss.

I think my biggest concern here is baking the `TG4Event` into this repository.  I think this is unlikely to go well over the long run, because it means that it's possible to accidentally get skew between the version of `edep-sim` used in production and what we have here.  (And particularly the `.o` file that I see here, which would need to be rebuilt any time we change compiler architecture or toolchain etc.  I assume that was a just a commit mistake, since object files aren't really useful except as the inputs to libraries anyway.)  

Is there any particular reason you chose to do it this way, as opposed to the way `ND_CAFMaker` used to depend directly on `edep-sim` via UPS, and pull the `TG4Event` library from there?  I have a very strong bias towards the "old" way, because (a) it allows us to keep the dependencies straightforward, and (b) it streamlines the pathway towards eventual Spack-ification & AL9.  So unless we _can't_ do it that way, that's what I'd like us to do.

2024-08-29 16:38 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +
do we just lose the ancestor info altogether now?

2024-08-29 16:38 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +                            : truePartPassThrough.gen_id;
same idea as previous

2024-08-29 16:38 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +            truthMatch->GetTrueParticle(sr, srTrueInt, truePartPassThrough.gen_id, srPartCmp, true, !truthMatch->HaveGENIE());
I think the `!truthMatch->HaveGENIE()` needs to be replaced by a more complex condition---we only want to be creating a new particle if there's no GENIE _and_ (no edep-sim info, if we expect it), right?

2024-08-29 16:38 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +                            : truePartPassThrough.gen_id;
here again drop the `?:`

2024-08-29 16:38 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +          is_primary ? truthMatch->GetTrueParticle(sr, srTrueInt, truePartPassThrough.gen_id, srPartCmp, true, !truthMatch->HaveGENIE())
same comment as previous on `!HaveGENIE`

2024-08-30 04:33 UTC, noeroy commented on build.sh
So up to now, because we used a more recent version of duneanaobj that somewhat forced us to move to e26 we migrated everything except hdf5. That one still in e20 seem to work with our current builds but it's not optimal.

As we have a new version of duneanaobj to be built, I've asked tom if it was possible to also get it in e20 too with the older version of root we've been using.

2024-08-30 04:45 UTC, noeroy commented
About the main issue with the TG4Event Libraries. I've fixed it by just loading Edepsim with ups, I don't why I didn't do it originally. I checked that we got the same reasult with it.

2024-08-30 05:06 UTC, sindhu-ku commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
I think this might be a casting issue that I noticed in flow a while ago: https://docs.dunescience.org/cgi-bin/sso/RetrieveFile?docid=30569&filename=CAFissues_NDprotoypes_May16.pdf&version=1 (slide 4)
It was reported but not followed upon. I will open an issue. 
But it would be good to check which variables don't satisfy the condition i.e. just positions or other variables as well

2024-08-30 05:33 UTC, noeroy commented on src/truth/FillTruth.cxx
> +    (collection.at(part_index)).end_pos = (pf.Position * .1).Vect();
Done it

2024-08-30 05:34 UTC, noeroy commented on src/truth/FillTruth.cxx
> +    }
I've added some boolean and a function so that we load for the first access and not at the declaration.

2024-08-30 05:34 UTC, noeroy commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +
The ancestor is lost in some cases because MLReco doesn't store neutrals or particles tthat didn't interact in the argon so sometimes the ancestor link is lost. It's filled by Edepsim, however.

2024-08-30 05:42 UTC, noeroy commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +                            : truePartPassThrough.gen_id;
Fixed it.

2024-08-30 05:46 UTC, noeroy commented on src/truth/FillTruth.cxx
> +      if (HaveGENIE() && fEdepSimTree.GetEdepTree() )
Well we could do it differently asking for the existence of the edeptree before any call. But the truth information filled wouldn't be the same one and complete in that case.

2024-08-30 12:41 UTC, noeroy commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +            truthMatch->GetTrueParticle(sr, srTrueInt, truePartPassThrough.gen_id, srPartCmp, true, !truthMatch->HaveGENIE());
I've combined both.
I guess if we still want to keep a GENIE only version of MC truth we might need to be more cleaver.

2024-08-30 14:03 UTC, chenel commented on build.sh
Ok, thanks.  Yeah, I remember the hybrid version we've been working with, but I don't want to cement that yet, if we can avoid it.  Let me know what Tom says 👍🏻

2024-08-30 14:06 UTC, chenel commented on src/truth/FillTruth.cxx
> +      if (HaveGENIE() && fEdepSimTree.GetEdepTree() )
Yeah, I'm just thinking about cases where somebody wants to test something quickly and only has the GENIE files lying around.  Or maybe they want to do some pre-simulation truth-level study (they're interested in predicted rates for some cross section?).  Obviously it wouldn't be fully complete, but I wonder if it would still be useful to have this functionality.  If you think it's too much work to maintain, I'm willing to be argued down, but I wanted to at least think through whether always demanding edep-sim is the right move.  What do you think?

2024-08-30 14:07 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +
Ah!  I overlooked those lines in `FillTruth`.  Thanks. 👍🏻

2024-08-30 14:10 UTC, chenel commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +            truthMatch->GetTrueParticle(sr, srTrueInt, truePartPassThrough.gen_id, srPartCmp, true, !truthMatch->HaveGENIE());
Okay.  I'll leave this until we converge on the discussion on the previous point where that's the primary question.

2024-08-30 14:15 UTC, chenel commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
Hmm.  The issue that you found was definitely `float` precision (6 decimals) whereas differences of `1e-4` are larger.  So while it's possible they're related, it's not clear to me that they're definitely connected.

2024-08-30 15:37 UTC, noeroy commented on src/truth/FillTruth.cxx
> +      if (HaveGENIE() && fEdepSimTree.GetEdepTree() )
I do think that being able to get some test jobs faster without having to bother about yet another file could be a good thing indeed. 

Perhaps adding a warning when processing like "be careful it's a truth minimal version". It'll be simpler to study possible logs also.

 I don't think it would make sense to have a edepsim only version so I can just try to move the edepsim tests a bit further.

In that case I think we'd want to keep `!HaveGENIE()` only in the reco branches to create new primaries.

2024-08-30 15:48 UTC, chenel commented on src/truth/FillTruth.cxx
> +      if (HaveGENIE() && fEdepSimTree.GetEdepTree() )
Ok.  Sounds good.  I trust you to implement this correctly, just wanted to make sure we had thought it through.  Thanks!

2024-08-30 16:24 UTC, sindhu-ku commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
But for z it is around 1e-4. I agree needs more digging

2024-08-31 04:27 UTC, noeroy commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
So it seems to indeed to only cause an issue with positions. On the tests I've made it looks like we can go up to 1e-5 (bellow that it crash) but it's just a couple of files and not a 1k files test.

2024-08-31 04:31 UTC, sindhu-ku commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
Maybe it reduced? The plots I showed were actually for a single file

2024-08-31 04:44 UTC, noeroy commented on build.sh
Alright, he kindly made 2 versions, one with e26 in case we're ready to move on and one with e20 and old version of root if we want to keep with the old build.

I've tried reverting everything into e20, and things build+run properly. 
Also tried to build dev (with the flash info) with the new duneanaobj and it built without issues. So perhaps we can actually revert all to e20 without issues?

2024-09-03 02:57 UTC, noeroy commented on src/reco/MLNDLArRecoBranchFiller.cxx
> +            truthMatch->GetTrueParticle(sr, srTrueInt, truePartPassThrough.gen_id, srPartCmp, true, !truthMatch->HaveGENIE());
Left it to GENIE Only, It automatically fills the edepsim valuesif they are available

2024-09-03 11:23 UTC, chenel commented on src/truth/FillTruth.cxx
> +    const auto cmp = [](const double & a, const float &b) -> bool { return util::AreEqual(a, b, 1e-4, 1e-4); };
thanks for digging on this Noe.  Let's touch base later today at the workshop and decide what to do next.

2024-09-04 03:10 UTC, chenel approved these changes
Didn't realize I hadn't already approved.  Sorry about that!

2024-09-04 04:31 UTC, merged