Feature/track matching
DUNE/ND_CAFMaker pull request #86
Opened 2024-09-16 21:54 UTC by noeroy

Track matching algorithm added for 2x2 (spine and pandora) and Mx2.

Matching values and method are based on [DocDb 31970](https://docs.dunescience.org/cgi-bin/sso/ShowDocument?docid=31970). 

Modifications are: 
- MakeCaf -> Removed Matchers from the reco trigger branches (we don't store specific triggers for matchers)  and then called the matcher after all reco have filled their branches. 

- Matching is done in NDLArMINERvAMatchRecoFiller, with a matching in (Δθx, Δθy, Δx, Δy) done both for SPINE and Pandora (if one of them are missing no matching is done for it).

2024-09-17 13:18 UTC, chenel requested changes
Hmm.  I don't love the filler name string comparisons in this code; they're rather fragile and easily lost if somebody happens to change the name later.  I think a better approach would be to add a new required method to the `IRecoBranchFiller` interface called something like `FillerType` that returns a member of a new enum that we can use to differentiate them (obviously better names welcome---I came up with these with <30s thought):

```
enum class RecoFillerType
{
   Unknown,
   BaseReco,  ///<  Full reconstruction stack like SPINE or Pandora
   Matcher,     ///<  Post-hoc matching run across detectors, but not creating new trigger entries etc.
};
```

and then adding

```
  /// What type of IRecoBranchFiller is this?
  RecoFillerType  Filler Type() const = 0;
```

to the `IRecoBranchFiller` class.  Then the `Pandora`, `SPINE`, `MINERvA` recos will override it with

```
   RecoFillerType FillerType() const override { return RecoFillerType::BaseReco; }
```

while the matchers will instead return

```
   RecoFillerType FillerType() const override { return RecoFillerType::Matcher; }
```

Then the "type" of the filler is embedded directly in the code, which is a bit more maintainable and obvious, and harder to break accidentally.  I'll suggest the resulting changes to the code in this PR in line-by-line comments.

2024-09-17 13:18 UTC, chenel commented on src/makeCAF.C
> +    if (filler->GetName() == "LArTMSMatcher" || filler->GetName() == "LArMINERvAMatcher") continue; //We don't want to store a trigger from a Matcher algorithm
Per the general comment, this would become

```suggestion
  {
    if (filler->FillerType != RecoFillerType::BaseReco) continue; //We don't want to store a trigger from a Matcher algorithm
```

2024-09-17 13:18 UTC, chenel commented on src/makeCAF.C
> +      if (filler->GetName() == "LArTMSMatcher" || filler->GetName() == "LArMINERvAMatcher")
and this one would become

```suggestion
      if (filler->FillerType == RecoFillerType::Matcher)
```

2024-09-17 13:18 UTC, chenel commented on src/reco/NDLArMINERvAMatchRecoFiller.cxx
> +    double d_thetay = .09; // Maximum Angle difference wrt to y axis [rad];
Can we please make these configuration parameters instead of hard-coding??

2024-09-17 13:18 UTC, chenel commented on src/reco/NDLArMINERvAMatchRecoFiller.h
> +/// \author  J. Wolcott <jwolcott@fnal.gov> & F. Akbar <fakbar@ur.rochester.edu>
Need to update the copy-paste 😄

2024-09-18 18:08 UTC, noeroy commented on src/makeCAF.C
> +    if (filler->GetName() == "LArTMSMatcher" || filler->GetName() == "LArMINERvAMatcher") continue; //We don't want to store a trigger from a Matcher algorithm
Implemented

2024-09-18 18:09 UTC, noeroy commented on src/makeCAF.C
> +      if (filler->GetName() == "LArTMSMatcher" || filler->GetName() == "LArMINERvAMatcher")
Implemented

2024-09-18 18:09 UTC, noeroy commented on src/reco/NDLArMINERvAMatchRecoFiller.h
> +/// \author  J. Wolcott <jwolcott@fnal.gov> & F. Akbar <fakbar@ur.rochester.edu>
Fixed it

2024-09-18 18:24 UTC, noeroy commented on src/reco/NDLArMINERvAMatchRecoFiller.cxx
> +    double d_thetay = .09; // Maximum Angle difference wrt to y axis [rad];
Done, when TMS will do track matching we might want to have some common things, until now I've just created `TrackMatch` variables to store all of those and explained the default value from the docdb entry.

2024-09-18 18:33 UTC, chenel approved these changes
Looks good.  Thanks, as always, for humoring my pedantry 😄

2024-09-18 18:40 UTC, noeroy commented
Thanks for reviewing!

2024-09-18 18:40 UTC, merged